"""initial schema

Revision ID: 0f4937d2a980
Revises: 
Create Date: 2026-09-16 16:23:42.888264
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0f4937d2a980'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facilities_state_city', 'facilities', ['state', 'city'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mrn', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mrn')
    )
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('accepting_new_patients', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("npi ~ '^[0-9]{10}$'", name='ck_providers_npi_10_digits'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npi')
    )
    op.create_index('ix_providers_specialty_accepting', 'providers', ['specialty', 'accepting_new_patients'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('origin_facility_id', sa.Integer(), nullable=False),
    sa.Column('assigned_provider_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'accepted', 'scheduled', 'completed', 'cancelled', 'rejected', name='referral_status'), nullable=False),
    sa.Column('priority', sa.Enum('routine', 'urgent', 'emergent', name='referral_priority'), nullable=False),
    sa.Column('specialty_requested', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_facility_id'], ['facilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_referrals_patient', 'referrals', ['patient_id'], unique=False)
    op.create_index('ix_referrals_status_priority_created', 'referrals', ['status', 'priority', 'created_at'], unique=False)
    op.create_table('referral_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('draft', 'submitted', 'accepted', 'scheduled', 'completed', 'cancelled', 'rejected', name='referral_status'), nullable=True),
    sa.Column('to_status', sa.Enum('draft', 'submitted', 'accepted', 'scheduled', 'completed', 'cancelled', 'rejected', name='referral_status'), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_referral_events_referral_time', 'referral_events', ['referral_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_referral_events_referral_time', table_name='referral_events')
    op.drop_table('referral_events')
    op.drop_index('ix_referrals_status_priority_created', table_name='referrals')
    op.drop_index('ix_referrals_patient', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('ix_providers_specialty_accepting', table_name='providers')
    op.drop_table('providers')
    op.drop_table('patients')
    op.drop_index('ix_facilities_state_city', table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###

    # Autogenerate does not emit DROP TYPE for native enums, so without this a
    # downgrade leaves referral_status/referral_priority behind and the next
    # upgrade fails with DuplicateObject. Verified by the round-trip test in
    # docs/BACKUP-RESTORE.md.
    sa.Enum(name='referral_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='referral_priority').drop(op.get_bind(), checkfirst=True)
