"""add users table

Revision ID: a6ca29d19c0c
Revises: 0f4937d2a980
Create Date: 2026-09-23 12:11:15.779597
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a6ca29d19c0c'
down_revision: str | None = '0f4937d2a980'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'clinician', 'coordinator', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name='ck_users_email_lowercase'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
    # Autogenerate never emits DROP TYPE for native enums; without this a
    # downgrade -> upgrade round-trip fails with DuplicateObject.
    op.execute('DROP TYPE IF EXISTS user_role')
